### ISSUE TITLE
Games not loading

### ISSUE THREAD

**Issue by dragonskies** [bluesabre/sgt-launcher#5]
Ubuntu 20.04, Plasma Workspaces
Tried launching a couple of different games, launcher remains on loading screen
![image](https://user-images.githubusercontent.com/1761771/99411036-2a651980-28c1-11eb-849f-69eeb341c1fb.png)

**Comment by ChaseCai2001** [comment]
Maybe it's your network problem.

**Comment by Jaki143** [comment]
Same problem here. Output in konsole:
`~$ sgt-launcher
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sgtlauncher/SgtSocketLauncher.py", line 52, in callback
    withdrawn = self.wait_for_window_withdraw()
  File "/usr/lib/python3/dist-packages/sgtlauncher/SgtSocketLauncher.py", line 89, in wait_for_window_withdraw
    withdrawn = is_withdrawn(self.window_id)
  File "/usr/lib/python3/dist-packages/sgtlauncher/SgtSocketLauncher.py", line 178, in is_withdrawn
    withdrawn = not property_reply or property_value[0] == 0
TypeError: 'NoneType' object is not subscriptable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
    os.unlink(pr_filename)
PermissionError: [Errno 13] Keine Berechtigung: '/var/crash/_usr_games_sgt-launcher.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sgtlauncher/SgtSocketLauncher.py", line 52, in callback
    withdrawn = self.wait_for_window_withdraw()
  File "/usr/lib/python3/dist-packages/sgtlauncher/SgtSocketLauncher.py", line 89, in wait_for_window_withdraw
    withdrawn = is_withdrawn(self.window_id)
  File "/usr/lib/python3/dist-packages/sgtlauncher/SgtSocketLauncher.py", line 178, in is_withdrawn
    withdrawn = not property_reply or property_value[0] == 0
TypeError: 'NoneType' object is not subscriptable`

**Comment by bluesabre** [comment]
Verified on Kubuntu 20.04. Will investigate.
